#!/usr/bin/env bash
rm -rf /usr/share/gnome-shell/extensions/gnome-shell-theme.gresource
cp /usr/share/gnome-shell/extensions/gnome-shell-theme.gresource /usr/share/gnome-shell/extensions/gnome-shell-theme.gresource

gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable add-to-desktop@tommimon.github.com
gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
gnome-extensions enable dash-to-dock@micxgx.gmail.com
gnome-extensions enable gtk4-ding@smedius.gitlab.com
gnome-extensions enable just-perfection-desktop@just-perfection
gnome-extensions enable blur-my-shell@aunetx
gnome-extensions enable tiling-assistant@leleat-on-github
gnome-extensions enable arch-update@RaphaelRochet
gnome-extensions enable desktop-cube@schneegans.github.com
gnome-extensions enable blurmylightshell@dikasp.gitlab

gsettings set org.gnome.desktop.interface icon-theme 'Marwaita'
gsettings set org.gnome.desktop.interface cursor-theme 'SShell'

dconf write /org/gnome/shell/extensions/user-theme/name "'Default'"
dconf write /org/gnome/shell/extensions/arch-update/notify true

dconf write /org/gnome/shell/extensions/blur-my-shell/dash-to-dock/static-blur false

gsettings set org.gnome.shell welcome-dialog-last-shown-version '4294967295'
